### ISSUE TITLE
Escape key to quit

### ISSUE THREAD

**Issue by jtrv** [jantap/rsmixer#10]
Can you please add the escape key as a binding to quit rsmixer?

**Comment by maroider** [comment]
You can [configure your own keybindings](https://github.com/jantap/rsmixer#changing-keybindings).

**Comment by jtrv** [comment]
I apologize, not sure how I missed that. Great work on this, I really appreciate it and I appreciate the quick response to this lame issue.

**Comment by maroider** [comment]
I'm not really affiliated with this project, despite the "contributor" badge. I've just got this repo on "watch all activity" for some reason.
