### ISSUE TITLE
Mouse click and scroll for level change?

### ISSUE THREAD

**Issue by mxmilkiib** [jantap/rsmixer#6]
Would be pretty handy if the program could respond to mouse clicks and scrollwheels to change the volume levels!

**Comment by jantap** [comment]
Thought of adding that when I started the project , but completely forgot about it. Good feature and I'll definitely add it, however it will take a while (2-3 weeks) as I'm in the midst of a big refactor of the ui module. I'll keep you posted on the progress

**Comment by jantap** [comment]
done in v0.5.0
